### ISSUE TITLE
Explanation for Ranges

### ISSUE THREAD

**Issue by Geradav** [OfficeDev/office-scripts-docs#101]
In the section for Ranges (https://docs.microsoft.com/en-us/office/dev/scripts/develop/scripting-fundamentals#ranges)
It is explained that A1 notation refers to row A and column 1.
Shouldn't it be the contrary? The letter refers to column header and the number refers to row header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91eab22e-1a2a-a9e7-2331-f87462d64fcc
* Version Independent ID: bf0955e2-2a06-ea7d-3d78-c8c52294d23a
* Content: [Scripting fundamentals for Office Scripts in Excel on the web - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/develop/scripting-fundamentals#ranges)
* Content Source: [docs/develop/scripting-fundamentals.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/develop/scripting-fundamentals.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Geradav,
You are correct: letters denote columns. I'll make the changes and submit a PR soon.

**Comment by AlexJerabek** [comment]
Hi @Geradav, 
Thanks again for bringing this to our attention. The corrected text has been checked in. It will be on the live site soon.
Please let me know if you have any further issues.
