### ISSUE TITLE
Where are Scripts saved/stored?

### ISSUE THREAD

**Issue by onRubik** [OfficeDev/office-scripts-docs#156]
In the next documentation:
https://docs.microsoft.com/en-us/office/dev/scripts/overview/excel

It explains that the scripts can be saved, where are the scripts stored? is it the same Git Hub options as ScriptLab?, I need to know If I don't necessarily need a Git Hub account before asking my It Admin to enable the Automate Ribbon option

![script](https://user-images.githubusercontent.com/45592947/88561122-38c6b700-cfec-11ea-84b7-c11d53feffbf.PNG)

**Comment by AlexJerabek** [comment]
Hi @onRubik, 
Scripts are stored in your OneDrive. There's a [section in that article that mentions that](https://docs.microsoft.com/en-us/office/dev/scripts/overview/excel#sharing-scripts), but I'll look into making that more clear.

**Comment by onRubik** [comment]
thank you much
