### ISSUE TITLE
Automate tab not visible in excel for web

### ISSUE THREAD

**Issue by syedirfan1234-art** [OfficeDev/office-scripts-docs#165]
We have officescripts enabled for users in our organization still no user can see automate ribbon in excel for web.

## Article URL
https://docs.microsoft.com/en-us/office/dev/scripts/testing/platform-limits#third-party-cookies

## Issue
We have office scripts enabled for users in our organization still no user can see automate ribbon in excel for web.

We checked with various browsers with all cookies enabled and in private session as well. All users in organization faces issue.
Is the feature available for yet to deliver. If feature is available then why automate ribbon is not available for our users.

**Comment by AlexJerabek** [comment]
Hi @syedirfan1234-art, 
I'm sorry that you can't get access to the Automate tab. Just to verify, does your organization have one of the licenses listed in the "Before you begin" section of [Manage Office Scripts settings](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-office-scripts-settings?view=o365-worldwide)? Office Scripts are currently only available for a certain level of commercial or education license.

**Comment by syedirfan1234-art** [comment]
> es your organization hav

Hi Alex,

We have the option "let users automate their task in excel on web"  is checked. and also our users have o365 e3 license available.

Our users checked in various browsers and not even a single user able to find the "automate" tab in excel online.

Is this something not rolled out tenant wide. Please confirm.

**Comment by AlexJerabek** [comment]
Thanks @syedirfan1234-art.

@peronald, can you please investigate this?

**Comment by peronald** [comment]
Hi @syedirfan1234-art 
    The Office Scripts feature is just starting to roll out to the Targeted Release audience for organizations which is why your users may have not seen it yet. It is going to be slowly rolling out over the next few months so it may take awhile for your users to see the Automate tab. Hope that helps and let me know if you have any additional questions.

**Comment by syedirfan1234-art** [comment]
> Hi @syedirfan1234-art
> The Office Scripts feature is just starting to roll out to the Targeted Release audience for organizations which is why your users may have not seen it yet. It is going to be slowly rolling out over the next few months so it may take awhile for all your users to see the Automate tab. Hope that helps and let me know if you have any additional questions.

Thanks for the reply. The makes sense and we will wait till MS roll out this feature for us.

**Comment by syedirfan1234-art** [comment]
Issue resolved....
