### ISSUE TITLE
Code Editor and Record Actions

### ISSUE THREAD

**Issue by LielanC** [OfficeDev/office-scripts-docs#176]
We finally enabled and got the  automate ribbon in excel for web enabled however both Record Actions and Code Editor sub windows are not loading/are blank. Is the some additional setting than we need to install/enable?

Additional info: The help sub window does populate correctly, so not sure.

**Comment by AlexJerabek** [comment]
Hi @LielanC, 

Thanks for raising this issue. If the Automate tab is appearing, I'm assuming most of the requirements listed [here](https://docs.microsoft.com/office/dev/scripts/testing/troubleshooting#automate-tab-not-appearing-or-office-scripts-unavailable) are met, but are third-party cookies enabled for your browser? Also, which browser are you using?

**Comment by LielanC** [comment]
Thanks Alex, that is correct we have met the requirements. 

Currently due to group policies, they have disabled 
"Allow sites to save and read cookie data"
"Block third party cookies"
on Chrome. 

So it might be an option/ maybe another MS solution required? Will provide feedback if org allows it.

**Comment by LielanC** [comment]
Would the site to be added be 
https://appsforoffice.microsoft.com/
?

**Comment by AlexJerabek** [comment]
Thanks for the information @LielanC. @peronald, can you confirm if that's the site that needs to be allowed for Office Scripts cookies?

**Comment by peronald** [comment]
Hey @LielanC, you can find the site you need to add by opening a new workbook in Excel on the web and taking the part of the url before the first "/ ". So, for example, if the url looks like the below: 
    "https://contoso-my.sharepoint.com/:x:/r/personal/..."
you should add the "https://contoso-my.sharepoint.com/" as the site that can have third party cookies enabled. 

If that doesn't work, could you provide the session id of the Excel on the web session? To get the session id, in the Excel workbook, go to File > About and then you should see the id there.
