### ISSUE TITLE
How to transfer ownership for Office Scripts

### ISSUE THREAD

**Issue by JasonH-Msft** [OfficeDev/office-scripts-docs#179]
A common scenario is how Office Script ownership transfer should be handled when the Office script creator is no longer with the organization or for any reason an ownership transfer of the Office Script is desired.

## Issue

Please describe in detail how ownership transfer can be performed by Office Script owners and tenant administrators.  Include in the description what permissions are required, and whether it is possible to administratively transfer ownership from one user account to another.  And is Modern M365 group ownership supported for Office Scripts?  (If yes, please describe any transfer process relating to Group owned Scripts.)

Also describe default retention policy for Office Scripts after a user has left the organization and is deactivated in Azure Active Directory.   Reference: https://docs.microsoft.com/en-us/onedrive/retention-and-deletion  

<This topic will be critical for tenant administrators handling ownership transfers and is a proven support call generator.>

**Comment by AlexJerabek** [comment]
Hi @JasonH-Msft, 

This issue should be addressed in https://github.com/OfficeDev/office-scripts-docs/pull/186. We added a topic about Office Scripts file storage and ownership. It should be live and publicly visible in the next couple days.

If you have any other questions or feel that this PR does not sufficient answer you questions, please let me know. Thanks!
