### ISSUE TITLE
Office Scripts in Excel on the web

### ISSUE THREAD

**Issue by JasonH-Msft** [OfficeDev/office-scripts-docs#180]
Recommended add to existing article:  Scripts are stored in the  OneDrive /Documents/Office Scripts location of the Script owner.  They are saved as .osts extension.

## Article URL

https://docs.microsoft.com/en-us/office/dev/scripts/overview/excel 

## Issue

Notifying Office Script creators of the default location of Office script files will provide better visibility in locating and/or identifying the Office Script files in their OneDrive.  There may also be administrative or security related reasons to be able to identify what .osts files are and where they are located by default.

**Comment by AlexJerabek** [comment]
Hi @JasonH-Msft, 

This issue should be addressed in https://github.com/OfficeDev/office-scripts-docs/pull/186. We added a topic about Office Scripts file storage and ownership. It should be live and publicly visible in the next couple days.

If you have any other questions or feel that this PR does not sufficient answer you questions, please let me know. Thanks!
