### ISSUE TITLE
Making a copy of an Office Script

### ISSUE THREAD

**Issue by JasonH-Msft** [OfficeDev/office-scripts-docs#181]
Explain the concept of when and how to use “Make a Copy”.

## Article URL

Either create a new, separate article or add to “Learn the basics of Office Scripts”
https://docs.microsoft.com/en-us/office/dev/scripts/tutorials/excel-tutorial

## Issue

If you want to create a "template" script and later create independent copies of that template script, you must “Make a Copy” of the script.  This is important to understand in the use scenario where you want to make a workbook “template” with multiple copies and customize each copy’s script.

**Comment by AlexJerabek** [comment]
Hi @JasonH-Msft, 

This issue should be addressed in https://github.com/OfficeDev/office-scripts-docs/pull/186. We added a topic about Office Scripts file storage and ownership. It should be live and publicly visible in the next couple days.

If you have any other questions or feel that this PR does not sufficient answer you questions, please let me know. Thanks!
