### ISSUE TITLE
Sharing Office Scripts in Excel for the web

### ISSUE THREAD

**Issue by JasonH-Msft** [OfficeDev/office-scripts-docs#182]
see suggested correction in Issue section below

## Article URL

https://support.microsoft.com/en-us/office/sharing-office-scripts-in-excel-for-the-web-226eddbc-3a44-4540-acfe-fccda3d1122b

## Issue

Please be more precise for what access permissions this is true, "**Important:** Anyone with access to a workbook can view and run its attached scripts."  Perhaps instead should read, "Anyone with Edit access to a workbook..."  Users with Read access should be able to view the workbook but not be able to run scripts.

**Comment by AlexJerabek** [comment]
Thanks for reporting all these issues @JasonH-Msft. I'll look through them and either follow-up with you or address them in a forthcoming PR.

**Comment by AlexJerabek** [comment]
This clarification has been made to the support.microsoft.com article. Closing the issue.
