### ISSUE TITLE
Security of Office Scripts

### ISSUE THREAD

**Issue by ThoHog** [OfficeDev/office-scripts-docs#185]
Could you please offer more details concerning Office Scripts and Security? The statement "no JavaScript auth tokens can be shared with (office?) scripts" is a bit vague. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67a88dd6-c546-a6a7-9745-50bc60de2a9f
* Version Independent ID: 2274fc03-b644-8aa5-dd51-067ae86c9746
* Content: [Differences between Office Scripts and VBA macros - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/vba-differences)
* Content Source: [docs/resources/vba-differences.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/vba-differences.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @ThoHog. I'll work with the product team to bring better clarity to this document.

**Comment by AlexJerabek** [comment]
I added some clarity to the original statement in https://github.com/OfficeDev/office-scripts-docs/pull/187. Basically, there's no way for a script to authenticate with an external server - it can't use your existing information that you signed in to Excel with, and it can't make and send its own auth token.

I'm closing the issue, but I'm happy to field more questions on the subject, if you need.
