### ISSUE TITLE
Would be great if this page had a link to Sudhi's code samples on Github as well as other samples written by the community

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-scripts-docs#189]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0de752a-5e17-5c20-acd7-67f9726bc767
* Version Independent ID: 4304ad93-6811-7101-4077-7f3366ace997
* Content: [Sample scripts for Office Scripts in Excel on the web - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/excel-samples)
* Content Source: [docs/resources/excel-samples.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/excel-samples.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jakobpn. This page is intended to be a more centralized place to find sample scripts around key behaviors and features. We want to limit the external links, as that builds out a hard-to-track dependency chain.

Over the next couple weeks, we'll be publishing a "Sample Contributor Guide" to help foster community contributions here. We want to help sample authors create scripts that can be shared and used by the larger community, which means there are certain quality bars we need to establish. One of which is ensuring samples are tightly scoped; a long sample with many features is typically less useful than several small samples each showing a single feature.

I'll be sure to reach out to you for feedback on the guide. Thanks!
