### ISSUE TITLE
Issue with manually entering file path for .xlsx

### ISSUE THREAD

**Issue by km594** [OfficeDev/office-scripts-docs#191]
Great tutorial! Got it working ok, struggled with adding my file path though - I could only add through using the pop-up file-selection GUI, instead of entering my filepath maunally (i.e. same path for example "/TestFolder/task-reminder.xlsx" but it failed on testing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d5d64ce-91a7-5caa-89f4-d16acac667bd
* Version Independent ID: 07baec70-00d6-e47b-f73a-f52bb10fd92e
* Content: [Office Scripts sample scenario: Automated task reminders - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/scenarios/task-reminders)
* Content Source: [docs/resources/scenarios/task-reminders.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/scenarios/task-reminders.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @km594,

Thanks for reporting this issue. Let me do some investigation and I'll get back to you soon. Just to check, you have the same values for the **Location** and **Document Library** fields as the sample, right?

![image](https://user-images.githubusercontent.com/38896772/100674655-59947580-331a-11eb-92c2-d9bc491f7890.png)

**Comment by AlexJerabek** [comment]
I just reproed this issue: Manually entering the file path caused the flow to fail, whereas using the file picker lead to success.

@danielgwilson, is this a Power Automate issue that you've encountered before?

**Comment by km594** [comment]
Thanks OfficeDev/office-scripts-docs!
