### ISSUE TITLE
Code gives an error because of Argument Type

### ISSUE THREAD

**Issue by mhusk** [OfficeDev/office-scripts-docs#205]
[20, 42] Argument of type 'string | number | boolean' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db20932c-4680-4ee6-1299-4995d5151e5f
* Version Independent ID: 3ff9e767-2543-6a73-579e-c0ea53c15a0c
* Content: [Read workbook data with Office Scripts in Excel on the web - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/tutorials/excel-read-tutorial)
* Content Source: [docs/tutorials/excel-read-tutorial.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/tutorials/excel-read-tutorial.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for catching this @mhusk. There was a recent change to the API that changed the return type of `getValue` from `any` to `string | number | boolean`. The script will still run, despite that compiler error.

I'll fix the tutorial to avoid that issue and submit a PR soon.
