### ISSUE TITLE
Safari supported..or not?

### ISSUE THREAD

**Issue by JasonH-Msft** [OfficeDev/office-scripts-docs#236]
[Enter feedback here]
In conversation with Petra, my understanding is Safari is not supported due to disallowing 3rd party cookies by default.  However Safari's inclusion here doesn't make that point clear, so if it is accurate that Safari is still not supported at present, then this should be stated and explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4085c6ff-856c-4704-8d72-5ef0ca1f64c1
* Version Independent ID: 92eda514-0e20-3add-4b61-62d82d210549
* Content: [Platform limits and requirements with Office Scripts - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/testing/platform-limits)
* Content Source: [docs/testing/platform-limits.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/testing/platform-limits.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @JasonH-Msft, 

As far as I understand, you should be able to allow 3rd party cookies in Safari by following these steps: https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac

Are you still unable to use Office Scripts after making that change?

**Comment by AlexJerabek** [comment]
Tagging @peronald too, since she was involved in the original discussion.

**Comment by JasonH-Msft** [comment]
Yes the feedback we need is from Petra.  😊  I want clarify whether we are supporting Safari.  I had a note from a previous meeting that we were NOT but if that has changed, that’s good to know.

**Comment by JasonH-Msft** [comment]
This was answered today, can be closed.  Thanks!
