### ISSUE TITLE
request features

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-scripts-docs#240]
"Request features" at https://aka.ms/oscripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67f2ac9-6bd4-a5fc-20b0-e0b055dbe61c
* Version Independent ID: a0f30a07-4ebf-ac33-6797-43ae7306bede
* Content: [Office Scripts documentation](https://docs.microsoft.com/en-us/office/dev/scripts/)
* Content Source: [docs/index.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/index.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

Can you please reach out internally and explain this feature request end point? Who requested it, who is monitoring it, etc.? Thanks!

**Comment by rootsmusic** [comment]
@AlexJerabek, https://aka.ms/oscripts is linked to "give feedback" on https://developer.microsoft.com/en-us/office-scripts
