### ISSUE TITLE
[LOC]Back-Translation "パワー自動化"→"Power Automate" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [OfficeDev/office-scripts-docs#257]
ja-jp:"https://docs.microsoft.com/ja-jp/office/dev/scripts/develop/power-automate-integration"
![power-automate-integration_j](https://user-images.githubusercontent.com/40815708/114292799-2fbf3c80-9acc-11eb-8d2b-7e82b07a7273.png)

en-us:"https://docs.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration"
![power-automate-integration_e](https://user-images.githubusercontent.com/40815708/114292806-36e64a80-9acc-11eb-8969-5ba7973c9f6f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0230f03f-497b-4a75-39f3-e56ee35994f0
* Version Independent ID: d10d4fe1-8786-c767-a038-075bd9c9d04a
* Content: [Run Office Scripts with Power Automate - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration)
* Content Source: [docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/develop/power-automate-integration.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @hyoshioka0128, 

Thank you for reporting this. I've alerted our localization team to the issue. We'll get back to you soon.

**Comment by AlexJerabek** [comment]
This looks to be an over-localization issue across multiple languages. It is being investigated by the localization team ([internal tracking link](https://microsoft.visualstudio.com/OS/_workitems/edit/32470398)).

I'll try to update the thread as we work on a fix.

**Comment by AlexJerabek** [comment]
Hello @hyoshioka0128, 

This localization issue should be fixed now. Please let me know if there are any other problems. 

I will close the issue, but please reply or create a new issue if you discover something else.

**Comment by hyoshioka0128** [comment]
@AlexJerabek - Thanks!
