### ISSUE TITLE
[LOC]Fixed inappropriate japanese "Power Automate Office"→"PowerAutomate を使用して Office" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [OfficeDev/office-scripts-docs#261]
[LOC]Fixed inappropriate japanese "Power Automate Office スクリプトを実行する"→"PowerAutomate を使用して Office スクリプトを実行する" (ja-jp)

related:#257
ja-jp:"https://docs.microsoft.com/ja-jp/office/dev/scripts/develop/power-automate-integration"
![power-automate-integration_j2](https://user-images.githubusercontent.com/40815708/115002248-7acbbc00-9edf-11eb-9408-19714e154eac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0230f03f-497b-4a75-39f3-e56ee35994f0
* Version Independent ID: d10d4fe1-8786-c767-a038-075bd9c9d04a
* Content: [Run Office Scripts with Power Automate - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration)
* Content Source: [docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/develop/power-automate-integration.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @hyoshioka0128. I have one again passed it along to our localization team for analysis.

**Comment by hyoshioka0128** [comment]
@AlexJerabek - Corrected. Thnks!
Closed #261.
