### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by Durgesh1402** [OfficeDev/office-scripts-docs#263]
Hi,

How to insert an image from one sheet to another by script?
or
How to insert an image from the folder to the excel sheet by script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0de752a-5e17-5c20-acd7-67f9726bc767
* Version Independent ID: 4304ad93-6811-7101-4077-7f3366ace997
* Content: [Basic scripts for Office Scripts in Excel on the web - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/excel-samples)
* Content Source: [docs/resources/excel-samples.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/excel-samples.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Durgesh1402 Thanks for asking about this.

@sumurthy Can you provide any guidance or example here?

Thanks.

**Comment by mscharlock** [comment]
Following up @sumurthy :)

**Comment by AlexJerabek** [comment]
Hi @Durgesh1402,

Here's a sample script to copy an image from one worksheet to another:
```TypeScript
/**
 * This script transfers an image from one worksheet to another.
 */
function main(workbook: ExcelScript.Workbook)
{
  // Get the worksheet with the image on it.
  let firstWorksheet = workbook.getWorksheet("FirstSheet");

  // Get the first image from the worksheet.
  // If a script added the image, you could add a name to make it easier to find.
  let image: ExcelScript.Image;
  firstWorksheet.getShapes().forEach((shape, index) => {
    if (shape.getType() === ExcelScript.ShapeType.image) {
      image = shape.getImage();
      return;
    }
  });

  // Copy the image to another worksheet.
  image.getShape().copyTo("SecondSheet");
}
```

I'll look into the second scenario (insert an image from a folder) as well. In the meantime, you can use the Record Actions button to generate a script based on UI actions. So, you can record yourself inserting the image you want.

**Comment by AlexJerabek** [comment]
I've created an [internal work item ](https://office.visualstudio.com/OC/_workitems/edit/5094346) to add this sample to the docs in some capacity.
