### ISSUE TITLE
Request for new article:  Restoring Deleted Office Scripts

### ISSUE THREAD

**Issue by JasonH-Msft** [OfficeDev/office-scripts-docs#280]
Could a new article be written on the topic of how to restore deleted scripts (from OneDrive)?  This will be a good reference for support when customers accidentally delete or troubleshoot when they don't see a Script they expect in the available scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea78ca2e-5171-be4b-1a76-16245c3cf186
* Version Independent ID: 4e25e34f-fa75-fbf5-ada5-12503a859cd1
* Content: [Troubleshooting Office Scripts - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/testing/troubleshooting#feedback)
* Content Source: [docs/testing/troubleshooting.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/testing/troubleshooting.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @JasonH-Msft, 

Thanks for the suggestion. You're right that this is done through the OneDrive file controls. I've added this request to our documentation backlog to consider how we link to that information and help Office Scripts customers discover that solution. 

Here's the [internal link to the work item](https://office.visualstudio.com/OC/_workitems/edit/5107272).
