### ISSUE TITLE
Steps 7-9 no longer up to date

### ISSUE THREAD

**Issue by nancy-wang** [OfficeDev/office-scripts-docs#290]
![image](https://user-images.githubusercontent.com/29635014/118550794-20668b00-b72b-11eb-9fef-ac4fde1ea1f0.png)

[We now automatically save a script after a user stops recording. The script details pane contains options to rename a script (hover over script name or look in the ... menu) and update its description]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64fba0bb-7700-99a1-4f48-93a320e6d1f1
* Version Independent ID: a765c9d0-1250-372d-b3ac-9e0911e2193e
* Content: [Record, edit, and create Office Scripts in Excel on the web - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/tutorials/excel-tutorial.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Fixed with #294.
