### ISSUE TITLE
Office Scripts as a "cross-platform solution" is a bit confusing

### ISSUE THREAD

**Issue by wamaina** [OfficeDev/office-scripts-docs#292]
## Article URL
https://docs.microsoft.com/en-us/office/dev/scripts/resources/vba-differences

## Issue
Today, Office Scripts doesn't have cross-platform support but we call this out as a guiding principle. Is this how we want the community to think of Office Scripts now?

**Comment by AlexJerabek** [comment]
@wamaina, good call.  I assume you're talking about the first line in the linked doc, right? I think this is your call of how we want to pitch the offering. I'm happy to change that to "web-first", if that would be a better message.
