### ISSUE TITLE
Should we provide a refence to a Power Automate tutorial?

### ISSUE THREAD

**Issue by wamaina** [OfficeDev/office-scripts-docs#295]
## Article URL
https://docs.microsoft.com/en-us/office/dev/scripts/resources/vba-differences

## Issue
We say you can use Power Automate but then don't provide a reference for those who might want to get started. Could we incorporate one on this?

**Comment by nancy-wang** [comment]
+1 - we hear a considerable amount of feedback that suggests Power Automate as a key differentiator with VBA; however, not everyone is familiar with Power Automate. Including a reference here could be a great way to showcase the breadth that these two tools have to offer

**Comment by AlexJerabek** [comment]
Fixed with #321.
