### ISSUE TITLE
Office Script TypeScript Restrictions in class definitions

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/office-scripts-docs#302]
The TypeScript restrictions page should include that Office Script methods may not be used inside class methods or as class properties or passed to class constructors.

## Article URL

https://docs.microsoft.com/en-us/office/dev/scripts/develop/typescript-restrictions

## Issue

Documentation should call out that classes may not use Office Script methods.

**Comment by AlexJerabek** [comment]
@wandyezj, is this in effect already? If not, I'd like to wait until the linter rule.

**Comment by AlexJerabek** [comment]
Hi @wandyezj,

I just tried this scenario and there is no linter error. To repro, add the following data to the top-left corner of a worksheet and run the following script:

**Data**:
|Employee | Salary|
|-- | --|
|Alex | 40000|
|Erik | 50000|
|Kelvin | 60000|

**Script**:
```
function main(workbook: ExcelScript.Workbook) {
  let allEmployees: Employee[] = [];
  for (let i = 2; i <= 4; i++) {
    allEmployees.push(new Employee(workbook.getActiveWorksheet().getRange(`A${i}:B${i}`)));
  }

  allEmployees.forEach((employee) => {
    employee.giveRaise(5);
  });
}

class Employee {
  row: ExcelScript.Range;
  
  constructor(row: ExcelScript.Range) {
    this.row = row;
  }

  giveRaise(raisePercentage: number){
    let salaryCell = this.row.getCell(0, 1);
    let currentSalary = salaryCell.getValue() as number;
    salaryCell.setValue(currentSalary * (1 + raisePercentage * .01));
  }
}
```

**Comment by wandyezj** [comment]
Correct there is no linter error at the moment. However, we should still consider documenting known edges.

https://stackoverflow.com/questions/68164078/why-does-my-function-return-type-turns-into-a-promise-once-i-read-cell-value-or

**Comment by AlexJerabek** [comment]
@wandyezj, Can you please provide a concise example of this problem?

**Comment by AlexJerabek** [comment]
Closing as part of #372
