### ISSUE TITLE
Image for 'Implicit Any'

### ISSUE THREAD

**Issue by jayrathi** [OfficeDev/office-scripts-docs#310]
It would be good to have an image for the implicit any error. There is also an option to 'Quick Fix' the error, we should point that out too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1910d2d4-8ab4-ea96-6836-6184e27df702
* Version Independent ID: b3c3914d-1206-c517-2f9f-6a0d96eeba0c
* Content: [TypeScript restrictions in Office Scripts - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/develop/typescript-restrictions)
* Content Source: [docs/develop/typescript-restrictions.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/develop/typescript-restrictions.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @jayrathi. I'll add the screenshot once the UI text update goes through.
