### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by smittypro** [OfficeDev/office-scripts-docs#35]

**Comment by AlexJerabek** [comment]
Hi @smittypro, Which link is broken?

**Comment by smittypro** [comment]
The one to that suggests the content should be viewed on docs.microsoft.com:

"For the best experience, we recommend you view this content on docs.microsoft.com." It goes here: https://docs.microsoft.com/en-us/office-scripts-docs, but gets a 404 Page not found error.

**Comment by AlexJerabek** [comment]
Gotcha. That will light up when the docs goes live.
