### ISSUE TITLE
Notes in "Overview" are overwhelming

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-scripts-docs#37]
Notes in overview are a bit overwhelming as a first-time reader; I'm expecting to see a very simple, rapid on-ramp towards (1) knowing "enough" and (2) trying the product out. I recommend significantly condensing or even omitting most of the Note content that is shown currently.

<img width="1440" alt="Screen Shot 2019-12-11 at 1 12 34 PM" src="https://user-images.githubusercontent.com/11265967/70660978-2b54ec00-1c18-11ea-8512-8878ccc245b1.png">

## Article URL
https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/overview/overview.md

**Comment by AlexJerabek** [comment]
Addressed by #46 .
