### ISSUE TITLE
Is *.xlsm file supported, and is it supported by other actions besides "Run script" action via Power Automate?

### ISSUE THREAD

**Issue by MiyukiAmino** [OfficeDev/office-scripts-docs#386]
[Enter feedback here]
questions:
 1. Is *.xlsm file supported via Power Automate?
 2. is it supported by other actions besides "Run script" action  via Power Automate?

There is a difference in the descriptions between this doc and Excel Online (Business) connector's doc, but which is correct?

Excel Online (Business) Connector says below:
'The connector supports files only in Microsoft Excel Open XML Spreadsheet format (*.xlsx).'

Excel Online (Business)
https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa04502-ef3e-5441-8057-6e7896a25d34
* Version Independent ID: e91faff4-49c5-6526-73e1-e0be034bae3d
* Content: [Use macro files in Power Automate flows - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/testing/macros-power-automate)
* Content Source: [docs/testing/macros-power-automate.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/testing/macros-power-automate.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@MiyukiAmino 
This scenario **_is_** supported in Power Automate. You can use .xlsm files with, and only with, the Run Script action of the Excel Online - Business connector using the steps listed in the article. Other actions on that connector do not support .xlsm files.

**Comment by MiyukiAmino** [comment]
Thanks, @AlexJerabek 
It's great to have more types of files to use in Power Automate! Could you please mention in this docs that only the Run script action can be used.

**Comment by MiyukiAmino** [comment]
And I'll request modifications to the connector doc as well.

**Comment by AlexJerabek** [comment]
Yes, I have created an [internal work item](https://office.visualstudio.com/OC/_workitems/edit/5342595) to track this documentation fix. I'll leave this issue open until that work is completed both in these docs and the connector documentation as well.

**Comment by MiyukiAmino** [comment]
Thank you so much!

**Comment by MiyukiAmino** [comment]
Hey, @AlexJerabek ! How is the matter going? :)

**Comment by AlexJerabek** [comment]
Hi @MiyukiAmino,
Sorry for the delay; I've been on leave the last couple weeks. I should have the documentation updated this week.
