### ISSUE TITLE
"Excel for the web" or "Excel on the web"?

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-scripts-docs#39]
Excel product name is inconsistent with other documentation; see:
- https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online
- https://products.office.com/en-us/free-office-online-for-the-web
- https://support.office.com/en-us/article/create-a-workbook-in-excel-for-the-web-63b50461-38c4-4c93-a17e-36998be0e3d0

(Google search suggests correct name is "Excel for the web")

**Comment by danielgwilson** [comment]
@Reezaali @AlexJerabek

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT Can you weigh in here?

**Comment by ElizabethSamuel-MSFT** [comment]
@danielgwilson Excel on the web, Excel for the web, using Excel in a web browser, and similar terms are all valid ways of representing what was formerly Excel Online or Excel Web App. Within the Office Add-ins docs, we decided that the preferred term is Excel on the web.
