### ISSUE TITLE
relink "request features"

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-scripts-docs#397]
Link to "request features" redirects to retirement of UserVoice.  See link to "give feedback" (under "get resources") at https://developer.microsoft.com/en-us/office-scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67f2ac9-6bd4-a5fc-20b0-e0b055dbe61c
* Version Independent ID: a0f30a07-4ebf-ac33-6797-43ae7306bede
* Content: [Office Scripts documentation](https://docs.microsoft.com/en-us/office/dev/scripts/)
* Content Source: [docs/overview/index.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/index.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @rootsmusic. I'll find out the correct place to request features and update the links.

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

Thanks again for raising this issue. The current guidance for feature requests is to raise them in Excel. Use the **Send feedback** button in the Code Editor's overflow menu (**...**).

![image](https://user-images.githubusercontent.com/38896772/133502676-3ba16b1b-c733-4f1e-b9e6-11fe91324eed.png)
