### ISSUE TITLE
"Overview" missing top-level "what is this thing" section

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-scripts-docs#40]
When viewing the "Overview" page, I'm expecting to see a broad "what is this thing" section, followed by in-depth sections on what I need to know. Currently, I think the article does a good job with the in-depth sections, but omits a broader first section that is more detailed than the index, but less than the current sections.

E.g.

#### What can Office Scripts be used for?

_Examples, gifs, motivate why this is awesome_

#### Why is this useful?

_Maybe case examples? Defer to Power Automate marketing approaches/docs framing_

#### Who is Office Scripts meant for?

_Brief overview of baseline skill sets required for certain things_

#### How does Office Scripts work?

_Outline the components and their general functions—current sections would probably be subsections here._

## Article URL
https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/overview/overview.md

**Comment by AlexJerabek** [comment]
Fixed with #56
