### ISSUE TITLE
why Dx0nn1FelFp sheets are getting created in combined workbook.?

### ISSUE THREAD

**Issue by AbinashBehera27** [OfficeDev/office-scripts-docs#404]
Hi,
I have created a flow in Power Automate to combine two different workbooks having each 1 sheet, into a single workbook containing each of the sheets.  
While The flow gets succeeded, but two extra sheets get added into the Workbook named "workbooks1.Dx0nn1FelFp" and "workbook2.Dx0nn1FelFp" . How can we ignore these two sheets.
Please suggest.

Thank You,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688cb5b0-672f-8480-8943-6e4bc403d6b9
* Version Independent ID: 61518540-2796-b66f-4bc7-aef0eca420ad
* Content: [Combine workbooks into a single workbook - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook)
* Content Source: [docs/resources/samples/combine-worksheets-into-single-workbook.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/samples/combine-worksheets-into-single-workbook.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AbinashBehera27** [comment]
Hi Alex, 
Thank you for your reply,

1. No, these worksheets are coming from no where, its neither present in Original workbooks nor it was there in combined workbook before running the flow.
2. For Run Script 2, I have clicked **Switch to input entire array button** button for the worksheetInformation option. and given value as results(dynamic content) from previous step(excel run script).


The content of these additional workbook is something like this: **merpalert83 : {LikelihoodValues:{},Classification:,Keyword:[]}**

--83 is a number changing for each sheet, i.e. 83,84,85

Thank You,
Abinash

**Comment by AlexJerabek** [comment]
Thanks @AbinashBehera27. That helps narrow things down.

Have you made any changes to the sample scripts? If so, could you post your script? My thought is that the the worksheet name is getting a different value somehow. The sheet name looks like a function pointer or some other internal reference.

As a debugging step, you can also add a console.log statement to the end of the **Return worksheet data** script. That will make sure the worksheet name is getting exported correctly and rule out the first script as the problem area.

![image](https://user-images.githubusercontent.com/38896772/134961071-e9bbbe2f-d72b-43f5-872c-7e6799de5625.png)
