### ISSUE TITLE
obsolete typescript link  

### ISSUE THREAD

**Issue by yaron-sam** [OfficeDev/office-scripts-docs#408]
all linked page in typescript website have this message "This page has been deprecated"

## Article URL
https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/includes/coding-basics-references.md 

## Issue
all typescript  page has been deprecated. need to update the link

**Comment by AlexJerabek** [comment]
Thanks for reporting this @yaron-sam. I'll fix the links.
