### ISSUE TITLE
"Overview" "Script environment" section is unhelpful if unfamiliar with TypeScript

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-scripts-docs#42]
Becomes more obvious if you read it from the persona of "I only know Excel, I've never programmed before (or I've used VBA a few times)."

Suggest emphasizing TypeScript less and giving a brief overview of what it is with a link to the TypeScript site.

https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/overview/overview.md

**Comment by AlexJerabek** [comment]
Addressed by #46 .
