### ISSUE TITLE
A for -while- incrementing loop please.

### ISSUE THREAD

**Issue by Sotapanna** [OfficeDev/office-scripts-docs#426]

**Comment by AlexJerabek** [comment]
Hi @Sotapanna,

Thank you for the documentation request. Could you please provide more context on what scenario you need assistance with? We have some examples of incrementing `for` loops in the samples, such as this one that shows how to [Change each individual cell in a range](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-samples#change-each-individual-cell-in-a-range). However, if there's a particular scenario, I can look into making a sample for that.

In general, loops in Office Scripts are the same as in TypeScript/JavaScript. All the information from the MDN web docs about [Loops and Iteration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration) should be helpful for learning the syntax beyond your specific scenario.

Thanks!
