### ISSUE TITLE
Macro examples

### ISSUE THREAD

**Issue by dalfaand** [OfficeDev/office-scripts-docs#475]
Hello,

Would it be possible to give some examples of macros that work with this Power Automate action? I've tried some simple VBA Subs and Functions but the scripts are not detected through the metadata Id.

Thanks,
Diego

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223ead84-90d7-4705-e878-2fd1684d8395
* Version Independent ID: fd69b73c-4356-1fd6-43ab-c13eefc426b4
* Content: [Use macro files in Power Automate flows - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/develop/macros-power-automate)
* Content Source: [docs/develop/macros-power-automate.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/macros-power-automate.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @dalfaand,

Thank you for reporting this issue. I have reached out to the product team to try and get some examples and more guidance about this scenario.

**Comment by AlexJerabek** [comment]
Hi @dalfaand,

Macros cannot be run through Power Automate. This article is describing that Office Scripts (the web-based automate solution) can be run on .xlsm files through Power Automate and the extra step needed to make that happen.

I agree that the documentation is misleading here. I'll leave this issue open and work to update it. Thank you.
