### ISSUE TITLE
Office Script to convert csv to excel file 

### ISSUE THREAD

**Issue by Xochipilli0** [OfficeDev/office-scripts-docs#479]
Hi, in the Microsoft support page tackling the above issue, there are two scripts, the second one supposedly slower but with greater flexibility for csv files having different number of columns in each line. The pb is that it look like the two scripts are identical...
Where is the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fdee872-3dfe-61b6-f824-dc8c74625c36
* Version Independent ID: c4481c81-ebae-7b3a-5da9-1757fb575188
* Content: [Convert CSV files to Excel workbooks - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv)
* Content Source: [docs/resources/samples/convert-csv.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/convert-csv.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Xochipilli0,

The difference between the two scripts was calling a `setValues` statement inside of a loop. There was an inaccurate assumption that behavior would force the script to communicate with the Excel workbook, meaning a network synchronization would happen for every row. However, those calls are intelligently batched by the compiled version of the script.

https://github.com/OfficeDev/office-scripts-docs/pull/471 is consolidating the sample down to one version. I'll close this issue once that gets checked in.

**Comment by AlexJerabek** [comment]
https://github.com/OfficeDev/office-scripts-docs/pull/471 has been checked in, so I'll close this issue. Please let me know if you have further questions.
