### ISSUE TITLE
"Sample code: Return table data as JSON" does not work

### ISSUE THREAD

**Issue by yutao-huang** [OfficeDev/office-scripts-docs#498]
A customer [reported that the first sample code on this page does not work](https://docs.microsoft.com/en-us/answers/questions/865071/34sample-code-return-table-data-as-json34-does-not.html). I was able to repro it. I provided the customer a temporary workaround but I believe there should be a better fix for that.

I didn't test the other samples on this page, but I assume they are probably also broken based on their similarities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ab721c-371b-8901-abdc-adbbcbd2c81b
* Version Independent ID: 5cd477ae-cce5-a942-4297-6f23aebd3267
* Content: [Output Excel data as JSON - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/get-table-data#sample-code-return-table-data-as-json)
* Content Source: [docs/resources/samples/get-table-data.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/get-table-data.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by nancy-wang** [comment]
Thanks @yutao-huang! Tagging @AlexJerabek as I think this might merit a docs update addressing the implicit any error in our samples

**Comment by AlexJerabek** [comment]
Thanks @nancy-wang and @yutao-huang. I've created a temporary fix with #500. I have a longer-term work item to rework the entire scripts+JSON story that should be completed this month.
