### ISSUE TITLE
Office Script - Power Automate - Keys parameter...

### ISSUE THREAD

**Issue by dmcgimpsey** [OfficeDev/office-scripts-docs#502]
Hi Team:

I am trying to run the sample script that was provided to do Excel Cross reference.

I am confused about step 2 where you need to enter the keys:

https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-cross-reference

In the example, it is an excel file, but I am not sure what the result.xlsx is referring to?   Do I need to build it and create a table?

Thanks

Don

![image](https://user-images.githubusercontent.com/13887014/172199997-6e47106e-ef43-4360-9961-fa7a482194f9.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0230f03f-497b-4a75-39f3-e56ee35994f0
* Version Independent ID: d10d4fe1-8786-c767-a038-075bd9c9d04a
* Content: [Run Office Scripts with Power Automate - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration)
* Content Source: [docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/power-automate-integration.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @dmcgimpsey,

The value being passed to "keys" is the returned value from the first "Run script" block. This is the data being returned by the "
"Get Event Data" script. It looks like an Excel file in the Power Automate UI to indicate it's a value from that Excel connector. 

To directly answer your question, you do not need to build the table or create a third Excel file. This sample shows a script passing data to another script in a different workbook.

Please let me know if that clarifies things for you.

**Comment by dmcgimpsey** [comment]
Thank you very much for the prompt reply.   These office scripts are new to me - I am still learning a lot - but I love it.

**Comment by AlexJerabek** [comment]
Of course! There's a lot of cool stuff to do with Office Scripts and Power Automate, which means there's a lot to learn. Please continue to share what's confusing to you so we can refine our documentation. I'll take a pass on that sample you referenced and make sure the result parameter is clearly defined and explained.

**Comment by dmcgimpsey** [comment]
Hi Alex, I have got it to work as designed.   I am attempting to build a multi-step validation script or process.  There are several parts to it and getting each part to work has been a lot of problem-solving, and searching for answers.    The use case is as follows:    Each day, there is a PDF form that is received that contains an list of transactions for the day.   I have an AI model that reads the form and creates a master repository for all the forms.   I have tracking number and dates plus line number to identify each line.    Then I receive individual bar codes that contain a reference number only - I have to lookup the ID from an oracle database, and match that ID to the first form (transaction file) ... then I flag the master file that the record was found.

I have had problems passing parameters into the Oracle query and secondly, I am not exactly sure how to pass the result of the query to another table.    As of now, I have a working version in Power BI that does a bunch of merges to do what I want, but it is not 100 percent automated, and I have to run the Oracle queries manually.    What I need to figure out is how to pass the Oracle results to Excel and also how to pass parameters into Oracle.

**Comment by AlexJerabek** [comment]
Thanks for sharing the scenario @dmcgimpsey. If you encounter challenges building that flow, I'd recommend the [Power  Automate forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). They're usually really responsive and helpful. Members of the Office Scripts product also patrol those forums looking for Excel-specific questions.

I cleaned up the original sample article in question. Those changes will be merged to the live site soon. I'll close this issue, but please reach back out if you have further questions.
