### ISSUE TITLE
Script fails; getTables() always returns empty array

### ISSUE THREAD

**Issue by IB-CDP** [OfficeDev/office-scripts-docs#527]
'Return Table Data as JSON' script fails on line 12.
`getTables()` seems to always return an empty array.

Can reproduce in new file running the following:
````
function main(workbook: ExcelScript.Workbook){  
  console.log(workbook.getWorksheet("Sheet1").getTables()); // logs " [] "
}
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ab721c-371b-8901-abdc-adbbcbd2c81b
* Version Independent ID: 5cd477ae-cce5-a942-4297-6f23aebd3267
* Content: [Output Excel data as JSON - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/get-table-data)
* Content Source: [docs/resources/samples/get-table-data.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/get-table-data.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. For Excel API issue, please ask it on https://github.com/OfficeDev/office-js.
There's no getTables API on sheet level. You can use sheet.tables instead. 
BTW, you can use range.getTables. Please refer to https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-gettables-member(1)

**Comment by IB-CDP** [comment]
> There's no getTables API on sheet level. You can use sheet.tables instead.

The script in the example [here](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/get-table-data) uses getTables() on a sheet. 

<img width="755" alt="Screen Shot 2022-07-28 at 8 20 16 AM" src="https://user-images.githubusercontent.com/110113745/181503476-59df2b00-a223-4e16-b555-10aff592ae53.png">

**Comment by JinghuiMS** [comment]
Thanks for clarifying your question. This is office script area issue. 
@wamaina Would you please help to take a look at this issue? Thanks!

**Comment by jeremy-msft** [comment]
Tagging @AlexJerabek to help.

**Comment by AlexJerabek** [comment]
Hi @IB-CDP,

Thanks for creating this issue. Are you using the workbook mentioned on the sample page [here](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/get-table-data#sample-excel-file)? 

If the worksheet doesn't have any tables, it'll return an empty array (represented in the console by "[]"), preventing the script from doing anything. If you add a table to your worksheet and run the script you provided in your initial post, you'll get console output like this:

![image](https://user-images.githubusercontent.com/38896772/183509716-4c6da607-14c2-40b0-a467-e3bd684c28f4.png)

If you don't know if the table will be in your worksheet, you can check to make sure it exists before continuing. That looks like this:

```
function main(workbook: ExcelScript.Workbook) {
    const tables = workbook.getWorksheet("Sheet1").getTables();
    if (tables.length === 0) {
        console.log("No tables are in the worksheet.");
        return;
    }

    // Continue
}
```

Does that help clarify? Please let me know if I'm misinterpreting your issue.

**Comment by IB-CDP** [comment]
🤦‍♂️ Completely missed that tables were specific user-made constructs within sheets. Not sure what I was thinking. New to Excel 😬

[JinghuiMS](https://github.com/JinghuiMS), FWIW, getTables() does seem work as documented on the linked page.

Cheers all.
