### ISSUE TITLE
Feedback on: Call scripts from a manual Power Automate flow

### ISSUE THREAD

**Issue by starfieldscreensaver** [OfficeDev/office-scripts-docs#531]
Step 7. Refresh the page to see the results of the Power Automate.

Maybe add Step 8. Return to the workbook and refresh the page, you will now see the date and time in cells A1 and B2. Note the time may be off by several hours depending on the time zone settings for the workbook and Power Automate.

or something like that.

Thanks,
Matt
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b951170-8016-6d95-be28-575a0e728c4b
* Version Independent ID: 42b9d09a-9e39-f9ed-c278-d40982c8defc
* Content: [Call scripts from a manual Power Automate flow - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/tutorials/excel-power-automate-manual)
* Content Source: [docs/tutorials/excel-power-automate-manual.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/tutorials/excel-power-automate-manual.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the suggestion @starfieldscreensaver. I'll put together a PR to incorporate this.
