### ISSUE TITLE
Input parameters for code in Sample code: Add worksheets

### ISSUE THREAD

**Issue by starfieldscreensaver** [OfficeDev/office-scripts-docs#535]
On this
`function main(workbook: ExcelScript.Workbook, workbookName: string, worksheetInformation: WorksheetData[])
{`

the param workbookName implies a Workbook. What is being passed as 'name' is a worksheet name.

It caused a little confusion for me at first because I read it as passing a full workbook.
Not sure if its really worth changing but thought I bring it up.
I could actually still be wrong on this interpretation also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688cb5b0-672f-8480-8943-6e4bc403d6b9
* Version Independent ID: 61518540-2796-b66f-4bc7-aef0eca420ad
* Content: [Combine workbooks into a single workbook - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook)
* Content Source: [docs/resources/samples/combine-worksheets-into-single-workbook.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/combine-worksheets-into-single-workbook.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by starfieldscreensaver** [comment]
never mind!

**Comment by AlexJerabek** [comment]
Hi @starfieldscreensaver,

Glad a second read cleared things up. If you do have any ideas or suggestions to improve the clarity of the docs, we're happy to hear them.
