### ISSUE TITLE
Max request body size limit (30,000,000 bytes or 28.6MB) when running Office Scripts in Power Automate

### ISSUE THREAD

**Issue by yutao-huang** [OfficeDev/office-scripts-docs#554]
When running Office Scripts in Power Automate, the parameters passed into the Run script action can sometimes be very large and its request might get rejected by our service due to the [default ASP.NET Core max request body size limit - 30,000,000 bytes or 28.6MB](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestbodysize?view=aspnetcore-6.0#microsoft-aspnetcore-server-kestrel-core-kestrelserverlimits-maxrequestbodysize).

We have seen customer whose flow passes in a giant JSON (>40MB) as the script parameter and the request failed right away.

Should we callout this platform limit in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4085c6ff-856c-4704-8d72-5ef0ca1f64c1
* Version Independent ID: 92eda514-0e20-3add-4b61-62d82d210549
* Content: [Platform limits and requirements with Office Scripts - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/testing/platform-limits)
* Content Source: [docs/testing/platform-limits.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/testing/platform-limits.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@yutao-huang PR #555 is ready for review, if you'd like to take a look.
