### ISSUE TITLE
OfficeScript Error

### ISSUE THREAD

**Issue by Pekotu** [OfficeDev/office-scripts-docs#572]
Hi, 
Could you help me please?
I tested office script manually (without Power Automate Flow) as you recommend and it work fine. But if I run it with Automate flow script stop with error. I'm using  your template files for testing. 
In output folder are created two new files "JulyGroups_.xlsx_" and "AugustGroups_.xlsx_". After manual extension change to .xlsx files are empty. 

Output of of Run script:
```
{
    "statusCode": 404,
    "headers": {
        "Access-Control-Expose-Headers": "Version",
        "mise-correlation-id": "79df18c5-532e-4f5f-9576-a9376d929e0f",
        "x-ms-workflow-name": "5fba9d55-ac0a-4321-906a-718f8c4f3d06",
        "Version": "3.6",
        "x-ms-client-request-id": "3b601724-9ebd-4323-bd0e-dd69fb097a3c",
        "x-ms-request-id": "3b601724-9ebd-4323-bd0e-dd69fb097a3c",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "false",
        "x-ms-apihub-obo": "false",
        "Cache-Control": "no-store, no-cache",
        "Date": "Sat, 21 Jan 2023 09:14:12 GMT",
        "Content-Length": "165",
        "Content-Type": "application/json"
    },
    "body": {
        "message": "We were unable to run the script. Please try again.\nWorkbook not found.\r\nclientRequestId: 3b601724-9ebd-4323-bd0e-dd69fb097a3c",
        "logs": []
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fdee872-3dfe-61b6-f824-dc8c74625c36
* Version Independent ID: c4481c81-ebae-7b3a-5da9-1757fb575188
* Content: [Convert CSV files to Excel workbooks - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv)
* Content Source: [docs/resources/samples/convert-csv.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/convert-csv.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Pekotu,

I'm sorry to hear you're having problems with the sample. It seems like something is wrong with those Excel files that are being created. Could you please share screenshots of your flow? The underscores in your file names seem suspicious.

For what it's worth, here's what the Apply-to-each loop my flow looks like:

![image](https://user-images.githubusercontent.com/38896772/214177585-021c8507-78eb-4b0c-b3b5-ab92b49da769.png)

**Comment by Pekotu** [comment]
Hi,
Thank you for messages.
Finally I solved it by removing of condition from flow. Now it use one csv and copy it to one xlsx and work fine.

Have a Great day

⁣Petr Kopecký


24. 1. 2023 0:48, 0:48, Alex Jerabek ***@***.***> napsal/a:

**Comment by ElizabethSamuel-MSFT** [comment]
@Pekotu Closing this issue as you seem to have resolved it. If you have further questions, do let us know. Thanks.
