### ISSUE TITLE
add Office add-ins to comparison table

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-scripts-docs#576]
COM add-ins and web add-ins aren't in the [comparison table](https://learn.microsoft.com/en-us/office/dev/scripts/resources/add-ins-differences#platform-support).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b86b664-868f-dfad-f362-396f1639d18e
* Version Independent ID: b2be8cd1-86b0-7915-5259-48512c69de98
* Content: [Differences between Office Scripts and Office Add-ins - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/add-ins-differences)
* Content Source: [docs/resources/add-ins-differences.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/add-ins-differences.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

Thank you for the feedback. I've updated the table as you have suggested. The documentation updates will roll out to the live site in the next couple days.

I'll close this issue now, but please let me know if you have further feedback.
