### ISSUE TITLE
Excel Scripts Table.addColumn() method example

### ISSUE THREAD

**Issue by pelowski** [OfficeDev/office-scripts-docs#581]
It would be great to see the syntax for using [the Table.addColumn method](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.table?view=office-scripts#excelscript-excelscript-table-addcolumn-member(1)) especially with table syntax.  

[The Dynamically reference table values example](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-samples#dynamically-reference-table-values) could benefit from this improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98c58cbf-aaf7-3d3a-48f4-ce9cebcf331c
* Version Independent ID: 74821d34-eab6-ec0f-7a9f-55aca81975d9
* Content: [Basic scripts for Office Scripts in Excel - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-samples#add-data-to-a-range)
* Content Source: [docs/resources/samples/excel-samples.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/excel-samples.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @pelowski,

Thank you for the request. I'll add a sample for the linked API. As for the comment about the dynamic reference, I think you'd be better off using the same pattern as in the current example. `Table.addColumn` can take an array for the column values, but if you're using the table reference syntax, you probably want to use a single value (not multiple in an array). You'd want to get the `Range` from the new column and use the same `setFormula` call in the previous sample.

I'll write up some code to demonstrate this.

**Comment by AlexJerabek** [comment]
Hi @pelowski,

I believe this script would help showcase the APIs you've suggested.

```
/**
 * This script adds a new column to a table.
 * It then sets the formulas in the new column to be the product
 * of the values in the two preceding columns.
 */
function main(workbook: ExcelScript.Workbook) {
  // Get the first table in the workbook.
  const table = workbook.getTables()[0];

  // Append an empty column to the table with the header "Total". 
  const totalColumn = table.addColumn(-1, null, "Total");

  // Get the names of the two preceding columns.
  const productColumnName1 = table.getColumns()[totalColumn.getIndex() - 1].getName();
  const productColumnName2 = table.getColumns()[totalColumn.getIndex() - 2].getName();
  
  // Set the formulas in the "Total" column to be the product of the two preceding columns.
  totalColumn.getRangeBetweenHeaderAndTotal().setFormula(`=[@[${productColumnName1}]]*[@[${productColumnName2}]]`);
}
```

 I've created https://github.com/OfficeDev/office-scripts-docs-reference/pull/251 to add this sample (and a simpler version for `Table.addColumn` ) to the reference documentation.

**Comment by AlexJerabek** [comment]
That PR is checked in. I'll close this issue, but if you have any follow-ups about the sample, I'm happy to reopen it.
