### ISSUE TITLE
Power Query additions/refreshes via ExcelScript?

### ISSUE THREAD

**Issue by pelowski** [OfficeDev/office-scripts-docs#582]
I'm guessing it's not possible because I don't see anything in the documentation but are there thoughts about being able to script/refresh/manipulate PowerQuery/M scripts using ExcelScript?  I can think of a number of different use cases for how I would use this.  Currently I have Excel templates (.xltx) that I deliver/share to colleagues to allow them to start basic queries to common data sources that we have.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98c58cbf-aaf7-3d3a-48f4-ce9cebcf331c
* Version Independent ID: 74821d34-eab6-ec0f-7a9f-55aca81975d9
* Content: [Basic scripts for Office Scripts in Excel - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-samples)
* Content Source: [docs/resources/samples/excel-samples.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/excel-samples.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @pelowski,

There are currently [PowerQuery APIs in the Office JS APIs](https://learn.microsoft.com/en-us/javascript/api/excel/excel.query?view=excel-js-preview). These APIs (used to make Office Add-ins) are what the Office Scripts APIs are based on (the Scripts APIs actually call the Office JS APIs under the hood). The functionality takes some time to port from the Office JS layer to Scripts and there are some other considerations that go into that porting decision (such as the APIs being supported cross-platform).

That said, I do not know when and if these Power Query APIs will make it into Scripts. I'll follow up internally to see if there's more information. If those JS APIs do not look like they'll help your scenario, it would be good to understand that as well.

**Comment by jokahati** [comment]
Hey @pelowski ,
Thanks for sharing your feedback.
As @AlexJerabek mentioned, we are investigating the connection space between Power Query and Office Scripts in Excel.
No timeline yet, but stay tuned for updates.
Thanks!
