### ISSUE TITLE
Excel for Windows

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-scripts-docs#585]
The Excel section is devoted only to Excel for the Web.  I'd consider Excel for Windows not supporting the Action Recorder to be a limitation though.

What about limits with backward compatibility (when a workbook with Office Scripts is opened in an older version of Excel)?  What if a workbook with Office Scripts is opened in a current version where the Automate tab isn't available (or has been disabled)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4085c6ff-856c-4704-8d72-5ef0ca1f64c1
* Version Independent ID: 92eda514-0e20-3add-4b61-62d82d210549
* Content: [Platform limits and requirements with Office Scripts - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/testing/platform-limits)
* Content Source: [docs/testing/platform-limits.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/testing/platform-limits.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @rootsmusic, thank you for submitting this issue! I've assigned it to the writer who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

For your first point about the Action Recorder, I can make that limitation clearer in the documentation.

For the question about backwards compatibility, I'll investigate internally. My understanding is that you won't be able to run or access Scripts on older versions of Excel, but there's no other consequence. I'll confirm with the feature crew.

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

I've created a couple PRs that refine my earlier answer. To answer your specific question, if you open a workbook with a script shared to it in a version without the Automate tab, nothing happens because there's no entry point.

Does that sufficiently answer your question? Or are their other backwards compatibility concerns you have?
