### ISSUE TITLE
Graph API

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-scripts-docs#590]
Is Microsoft Graph's API supported?  If yes, I suggest adding a [object model reference](https://learn.microsoft.com/en-us/office/vba/api/overview/excel/graph-visual-basic-reference).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f01b4871-30b7-89f6-7dbb-b91decd7fb41
* Version Independent ID: 41df3d49-f5da-14ed-96d0-7c80161131fd
* Content: [External API call support in Office Scripts - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/external-calls)
* Content Source: [docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/external-calls.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

Thanks for the question and sorry about the delay. Calls to the MS Graph from Office Scripts are not supported. There is no way to [make the authorization call from within a script](https://learn.microsoft.com/office/dev/scripts/develop/external-calls#limitations-with-external-calls-from-office-scripts). You'll have to use Power Automate to get Graph data and pass it to your script.
