### ISSUE TITLE
There is no 'Record Actions' button on the 'Automate' tab.

### ISSUE THREAD

**Issue by AlanPBourke** [OfficeDev/office-scripts-docs#599]
There is no 'Record Actions' button on the 'Automate' tab. Excel 2302.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64fba0bb-7700-99a1-4f48-93a320e6d1f1
* Version Independent ID: a765c9d0-1250-372d-b3ac-9e0911e2193e
* Content: [Record, edit, and create Office Scripts in Excel - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/tutorials/excel-tutorial.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for raising this issue @AlanPBourke. For Excel on Windows and Mac, the Action Record button is being rolled out over the next couple weeks. @gergzk, is there a particular build people should look for?

**Comment by AlexJerabek** [comment]
Hi @AlanPBourke,

I've created PR #602 to update the documentation to indicate the Action Recorder is being gradually rolled out over the next few weeks. We do this with new features to ensure product stability.

I'll remove the note once everyone has access to the recorder.

**Comment by emrefurkanozshn** [comment]
Hello Sir @AlexJerabek 
I do have the automate tab in my Excel, but my supervisor does not. We could not figure out the reason. Can you help out?
Thanks in advance

**Comment by AlexJerabek** [comment]
Sounds good! I saw that you also opened Issue #611. Please follow up on that open thread.
