### ISSUE TITLE
Code gives error

### ISSUE THREAD

**Issue by darrylvil** [OfficeDev/office-scripts-docs#600]
Hi there

the code in this script works on Excel desktop but returns an error when run in Excel Online or via Power Automate.

` for (let i = 0; i < dataRows.length; i++)`

Error
Cannot read properties of null (reading 'length')

Thanks
Dv
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2e9f5a-e7c8-b6b1-c3fa-c64934ca2eda
* Version Independent ID: 431cbb17-07a5-cead-41b0-e622672f5d63
* Content: [Move rows across tables using Office Scripts - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/move-rows-across-tables)
* Content Source: [docs/resources/samples/move-rows-across-tables.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/move-rows-across-tables.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @darrylvil. I'll investigate and report back.

**Comment by AlexJerabek** [comment]
Hi @darrylvil,

I'm unable to reproduce this issue on Excel on the web. Are you using the same workbook from the sample? If `dataRows` is null, that implies `Range.getValues()` returned null. I'm not sure what situation in which that happens. Could you provide a screenshot of the console window when running on the web?

**Comment by darrylvil** [comment]
Hi Alex

no, I'm using my own data. It runs fine in Excel desktop ok. But throws
that error in excel online.
(Microsoft® Excel® for Microsoft 365 MSO (Version 2302 Build
16.0.16130.20298) 64-bit)

[image: image.png]
Darryl Villaret
07776 194173

**Comment by darrylvil** [comment]
Hi Alex
Here’s the screenshot
Dv
![image](https://user-images.githubusercontent.com/129787786/229701758-5dc5b2b1-a8ab-451d-a436-fb77baf15fc8.png)

**Comment by vaquierm** [comment]
@darrylvil would you be able to share a screenshot or some details on the table (such as the dimension, if the totals row/header row is visible etc..) that you are running this script on? That would be helpful for us to try and reproduce the issue and try to troubleshoot it.

**Comment by darrylvil** [comment]
Hi I’m not sure not you mean by dimension? The the header row is visible. There is no total row. Would be easier if I shared the file with you?Regards DarrylOn 4 Apr 2023, at 19:25, Michael Vaquier ***@***.***> wrote:﻿
@darrylvil would you be able to share a screenshot or some details on the table (such as the dimension, if the totals row/header row is visible etc..) that you are running this script on? That would be helpful for us to try and reproduce the issue and try to troubleshoot it.

**Comment by darrylvil** [comment]
P.s. I have found another approach using queries to achieve what I need, so this is no longer an active problem for me. I’m still happy to help you troubleshoot it though if you want to try work it out. Regards DarrylOn 4 Apr 2023, at 19:25, Michael Vaquier ***@***.***> wrote:﻿
@darrylvil would you be able to share a screenshot or some details on the table (such as the dimension, if the totals row/header row is visible etc..) that you are running this script on? That would be helpful for us to try and reproduce the issue and try to troubleshoot it.

**Comment by vaquierm** [comment]
I'm happy to hear that you found a workaround!

If you are able to share a workbook that doesn't contain any of your data but still is able to reproduce the bug, that would be helpful. If not if you can tell us the address spanned by the table, that might be helpful as well.

**Comment by darrylvil** [comment]
Hi Alex, sorry for the delay, I've been away for a few days. Attached is a copy of the work book with one example line of data.
[Collar_data.xlsx](https://github.com/OfficeDev/office-scripts-docs/files/11189686/Collar_data.xlsx)

**Comment by AlexJerabek** [comment]
Hi @darrylvil,

Thank you for the sample workbook. I still haven't been able to reproduce your issue.  If you add `console.log(sourceRange.getAddress());` right after you create that range, what value gets returned (in the failing version)?
