### ISSUE TITLE
TypeScript version

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-scripts-docs#609]
Is Office Scripts tied to a specific version of TypeScript?  (VS Code for the Web is using TypeScript 5.0.1.)  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91eab22e-1a2a-a9e7-2331-f87462d64fcc
* Version Independent ID: bf0955e2-2a06-ea7d-3d78-c8c52294d23a
* Content: [Fundamentals for Office Scripts in Excel - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/scripting-fundamentals)
* Content Source: [docs/develop/scripting-fundamentals.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/scripting-fundamentals.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

Thank you for the question. I'll reach out to the product team and make sure the [licensing information file](https://github.com/OfficeDev/office-scripts-docs/blob/main/licensing-information.md) gets updated. In general, there's nothing binding Office Scripts to an older version of TypeScript and it will get regularly updated. Is there a particular feature you're curious about?

**Comment by rootsmusic** [comment]
No @AlexJerabek, you can close this issue.
