### ISSUE TITLE
Runtime error: Line 4: fetch is not defined

### ISSUE THREAD

**Issue by ireneqir** [OfficeDev/office-scripts-docs#610]
Add an image from a URL to a workbook, i just copy the code and put in my power automate-run script, it work well when it run from the excel workbook, but when put in power automate-run script, it show 'Runtime error: Line 4: fetch is not defined', why and please help

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95e77282-9af0-0646-e6ca-15b1615ff5f2
* Version Independent ID: 9822a8dd-90ef-2303-aaca-00ff8ceeb519
* Content: [Add images to a workbook - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/add-image-to-workbook)
* Content Source: [docs/resources/samples/add-image-to-workbook.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/add-image-to-workbook.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ireneqir,

Thanks for raising this issue. External calls, such as `fetch` aren't allowed when run through Power Automate, as documented here: https://learn.microsoft.com/en-us/office/dev/scripts/develop/external-calls#external-calls-from-power-automate.

This could be made clearer in the documentation. I'll leave this issue open until that's addressed.
