### ISSUE TITLE
In Excel Typescript / Javascript Add an image from a URL to a workbook code example works with URL images but not the local, how can I fix this? 

### ISSUE THREAD

**Issue by WhiteE4** [OfficeDev/office-scripts-docs#614]
Add an image from a URL to a workbook Excel TypeScript script

[## Article URL](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/add-image-to-workbook)

Add an image from a URL to a workbook code works with URL images but not the local, how can I fix this?

**Comment by WhiteE4** [comment]
async function main(workbook: ExcelScript.Workbook) {
  // Fetch the image from a URL.
  const link = "https://raw.githubusercontent.com/OfficeDev/office-scripts-docs/master/docs/images/git-octocat.png";
  const response = await fetch(link);

  // Store the response as an ArrayBuffer, since it is a raw image file.
  const data = await response.arrayBuffer();

  // Convert the image data into a base64-encoded string.
  const image = convertToBase64(data);

  // Add the image to a worksheet.
  workbook.getWorksheet("WebSheet").addImage(image);
}

/**
 * Converts an ArrayBuffer containing a .png image into a base64-encoded string.
 */
function convertToBase64(input: ArrayBuffer) {
  const uInt8Array = new Uint8Array(input);
  const count = uInt8Array.length;

  // Allocate the necessary space up front.
  const charCodeArray = new Array(count) as string[];
  
  // Convert every entry in the array to a character.
  for (let i = count; i >= 0; i--) { 
    charCodeArray[i] = String.fromCharCode(uInt8Array[i]);
  }

  // Convert the characters to base64.
  const base64 = btoa(charCodeArray.join(''));
  return base64;
}

**Comment by WhiteE4** [comment]
So apparently the Fetch approach doesn't work with local files

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @WhiteE4. I'm not sure your scenario of adding local files is possible, but I will check with the product team.

**Comment by AlexJerabek** [comment]
Hi @WhiteE4,

Working with local files through Office Scripts is not supported. This is a major difference between [Scripts and VBA](https://learn.microsoft.com/en-us/office/dev/scripts/resources/vba-differences?view=office-scripts), which was made for security purposes. You'll have to host your image file somewhere, though I believe you could use OneDrive or SharePoint. 

I'll update the documentation to make this restriction clearer.
