### ISSUE TITLE
Finally!  Something that gives me a clear example on how to use Power Automate to run a script that works

### ISSUE THREAD

**Issue by bocikt** [OfficeDev/office-scripts-docs#618]
Thank you for this tutorial.  I will be able to take this example and use it in my real world examples.  

I love step by step examples that actually work and reflect the applications I have.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b951170-8016-6d95-be28-575a0e728c4b
* Version Independent ID: 42b9d09a-9e39-f9ed-c278-d40982c8defc
* Content: [Call scripts from a manual Power Automate flow - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/tutorials/excel-power-automate-manual)
* Content Source: [docs/tutorials/excel-power-automate-manual.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/tutorials/excel-power-automate-manual.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @bocikt,

I'm glad to hear this was helpful! If you ever need any other samples or documentation to help with your Office Scripts scenarios, please don't hesitate to ask. Good luck learning Scripts and automating your workflows!
