### ISSUE TITLE
Add a known limitation for shared scripts

### ISSUE THREAD

**Issue by cwanja-msft** [OfficeDev/office-scripts-docs#623]
Maybe this is not the right page, but somewhere it should be noted that **Shared** Excel scripts cannot be called from Power Automate. Each user executing the Flow will be required to have their own "version" of the script, not a script stored on a SharePoint site or similar repository and then shared with them.

Have a Microsoft support ticket to refer to for more information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0230f03f-497b-4a75-39f3-e56ee35994f0
* Version Independent ID: d10d4fe1-8786-c767-a038-075bd9c9d04a
* Content: [Run Office Scripts with Power Automate - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration#see-also)
* Content Source: [docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/power-automate-integration.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@cwanja-msft Thanks for pointing this out.

@alison-mk Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Thanks for reporting this @cwanja-msft! I'll look into this an report back.

**Comment by alison-mk** [comment]
Hi @cwanja-msft, 

According to my research, the following is true: 

- A script stored in a user's **OneDrive** can't be used by another user in a Power Automate flow, unless the script author creates a Power Automate flow and explicitly shares that flow with additional users by (1) adding the additional users as owners of the flow, or (2) sharing the script author's credentials with the additional users. 
- However, scripts stored in **SharePoint** are fully supported in Power Automate through the "Run script from SharePoint library (Preview)" action. Scripts stored in SharePoint libraries are not limited to the script author. This action is currently in preview and may not yet be available to all users.

Do you have additional feedback or information that disagrees? If yes, could you provide the Microsoft support ticket details? 

Thanks, 
Alison

**Comment by cwanja-msft** [comment]
Thanks for investigating @alison-mk - that distinction is critical. Here is the internal ticket ID 2306260040011021, maybe you can validate what we informed the customer is true against your research? According to my support contact, the customer tried to upload a script to SharePoint and shared the script with the users and it still failed. Although, this wording might make it true-ish:
> This action is currently in preview and may not yet be available to all users.

**Comment by AlexJerabek** [comment]
Hi @cwanja-msft,

I've created a PR to update the documentation in a way that should make this restriction more clear: https://github.com/OfficeDev/office-scripts-docs/pull/633

As for the internal ticket, can you please follow-up with me (Alexander Jerabek) through email or Teams)?
