### ISSUE TITLE
Demo walkthrough doesn't work because Adaptive Card Action no longer exists

### ISSUE THREAD

**Issue by jessiewestlake** [OfficeDev/office-scripts-docs#625]
The demo instructs the user in instruction item 11 to create a new step with the action labeled **Post an Adaptive Card to a Teams user and wait for a response**, however, that card does not currently exist.

There is a similar card titled **Post adaptive card and wait for a response**, but that card has different required parameters than the ones described in instruction item 12. Instead of sending an Adaptive Card directly to a user, you must select who the message will be posted as and where it's posted to, even when setting the recipient to be a user by email.

How would we achieve the same effect as described in the demo?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d5d64ce-91a7-5caa-89f4-d16acac667bd
* Version Independent ID: 07baec70-00d6-e47b-f73a-f52bb10fd92e
* Content: [Office Scripts sample scenario: Automated task reminders - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/scenarios/task-reminders)
* Content Source: [docs/resources/scenarios/task-reminders.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/scenarios/task-reminders.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Thanks for reaching out, @jessiewestlake.

@alison-mk, could you please investigate this when you get a chance?

**Comment by alison-mk** [comment]
Hi @jessiewestlake, thanks for bringing this to our attention. I'm researching this issue and will report back when I have more information. 

Cheers, 
Alison

**Comment by AlexJerabek** [comment]
Looks like there's a new option in Power Automate. I'll start reworking the tutorial to use it.

**Comment by AlexJerabek** [comment]
Hi @jessiewestlake,
 
You're correct that the new "Post adaptive card and wait for a response" action is what you should be using. I've drafted a PR to clarify the changes. 

Here's what the action would look like: 
![scenario-task-reminders-2](https://github.com/OfficeDev/office-scripts-docs/assets/38896772/d20b3455-b9be-4ac3-b284-b1ac9101e226)
