### ISSUE TITLE
Error: Line 27: Table addRows: This won't work because it would move cells in a table on your worksheet.

### ISSUE THREAD

**Issue by kayliclegg** [OfficeDev/office-scripts-docs#654]
[Sample code: Combine data from multiple Excel tables in select worksheets into a single table](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/copy-tables-combine#sample-code-combine-data-from-multiple-excel-tables-in-select-worksheets-into-a-single-table)

I'm trying to use this code to combine multiple tables into a single table on one worksheet and all of it will run except for the last line:

if (rowCount > 0) {
                combinedTable.addRows(-1, dataValues);
                }

and it's giving me an error that says:

Line 27: Table addRows: This won't work because it would move cells in a table on your worksheet.

I don't know what this means and I don't know how to fix it.

please help.

**Comment by AlexJerabek** [comment]
Hi @kayliclegg,

Thanks for reporting this issue. I'll take a look at the sample and get back to you later today.

**Comment by AlexJerabek** [comment]
Hi @kayliclegg,

I tried to reproduce your issue but didn't get any errors. Are you using one of the workbooks from that sample?

**Comment by kayliclegg** [comment]
No I was using my own workbooks

**Comment by AlexJerabek** [comment]
Understood. Is the worksheet with the combined table otherwise empty? Or does it already have a table or other data?

**Comment by kayliclegg** [comment]
It is empty

**Comment by AlexJerabek** [comment]
@kayliclegg,

Could you help me understand what is different between your workbook and the sample workbook? Is that sample scenario working okay for you? Are you able to post a version that doesn't have any personal or private data?
