### ISSUE TITLE
Contradicting wording in docs?

### ISSUE THREAD

**Issue by KristianLN** [OfficeDev/office-scripts-docs#657]
Hi

In the Power Automate Toubleshooting docs ([here](https://learn.microsoft.com/en-us/office/dev/scripts/testing/power-automate-troubleshooting)) it is listed that the workbook.refreshAllDataConnections do nothing in Power Automate flows. However, just below it is stated that the workbook.refreshAllDataConnections only refreshes PowerBI sources. 
Isn't that contradicting?

![image](https://github.com/OfficeDev/office-scripts-docs/assets/36266464/65523d51-0e1e-49c5-bbf8-dbb16d052a11)

In advance, thank you.

Best regards,

Kristian

**Comment by AlexJerabek** [comment]
Hi @KristianLN,

You're right that there's a mistake there. Workbook.refreshAllDataConnections refresh PowerBI sources in Power Automate. I'll remove that line from the other table.

**Comment by KristianLN** [comment]
Hi Alex

Thank you for your reply.
For some reason, I experience the behaviour mentioned in the obsolete table line, namely that the script runs successfully, returns no error but don't update the pivot table through Power Automate.
Only when I open the file and runs the script, the table is updated.
Any ideas what is going on?

Best regards,

Kristian

**Comment by AlexJerabek** [comment]
Thanks for reporting this. @michelleranmsft, can you please investigate?

**Comment by AlexJerabek** [comment]
Hi @KristianLN,

The current behavior for Workbook.refreshAllDataConnections in Power Automate is that it only refreshes PowerBI sources. For other sources, the method returns successfully but does nothing.

I'll update the documentation to better explain that.

**Comment by KristianLN** [comment]
Hi Alex
Thank you for getting back to me.
The source is a Power BI source. 
What can I provide to show the issue?

**Comment by AlexJerabek** [comment]
Hi @KristianLN,
I'm checking internally about the best way to share this information. If you could report the issue through Excel (**Help** > **Feedback**), that would help.

**Comment by AlexJerabek** [comment]
@KristianLN,

When you create that feedback item, please include the client request ID from your flow run where the refresh failed.
