### ISSUE TITLE
The ability to simply update tables in XLSM is often inquired about - is it possible?

### ISSUE THREAD

**Issue by torevor** [OfficeDev/office-scripts-docs#662]
The title of this article implies that updating tables in xlsm workbooks from Power Automate is possible, but the content of the article is something else entirely.

It would perhaps be nice if Microsoft would reveal to its customers if it is or is not possible to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 223ead84-90d7-4705-e878-2fd1684d8395
* Version Independent ID: fd69b73c-4356-1fd6-43ab-c13eefc426b4
* Content: [Use macro-enabled files in Power Automate flows - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/macros-power-automate)
* Content Source: [docs/develop/macros-power-automate.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/macros-power-automate.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @torevor,

Thanks for raising this issue. I worked with the product team and determined that .xlsm files will work with the other Excel connector actions in Power Automate. You'll have to follow the instructions to get the file metadata to use as the file argument:
“Use the Get File Metadata action from either the [OneDrive for Business](https://make.powerautomate.com/connectors/shared_onedriveforbusiness/onedrive-for-business/) or [SharePoint](https://make.powerautomate.com/connectors/shared_sharepointonline/sharepoint/) connectors. Use the ID dynamic content returned from the Get file metadata action as the "File" argument for Excel connector actions.”

I'll leave this issue open while I update the documentation.
