### ISSUE TITLE
'Open in VSCode' doesn't work

### ISSUE THREAD

**Issue by pxntilde** [OfficeDev/office-scripts-docs#663]
I made a new script and selected "Open in VSCode" - it opened a new tab with VSCode successfully, but displays only the welcome page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a26d00f1-c759-a1fe-854f-a118a90359a0
* Version Independent ID: a26d00f1-c759-a1fe-854f-a118a90359a0
* Content: [Visual Studio Code for Office Scripts (preview) - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/vscode-for-scripts)
* Content Source: [docs/develop/vscode-for-scripts.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/vscode-for-scripts.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @pxntilde, 

Thanks for flagging this issue. I'll report it to the feature crew (@wandyezj).

**Comment by AlexJerabek** [comment]
Just wanted to ping the thread and say this is a known issue. A fix is still being investigated.

**Comment by AlexJerabek** [comment]
Hi @pxntilde,

Thanks again for reporting this. The Open in VS Code feature for Office Scripts has been removed. The timeline for reimplementing this feature is unclear. I created PR #672 to remove information about Open in VS Code from the documentation. This issue will close when that gets checked in.

**Comment by AlexJerabek** [comment]
Hi @HoldYourWaffle,

Please follow the [Excel Blog on Tech Community (with the Office Scripts tag)](https://techcommunity.microsoft.com/t5/excel-blog/bg-p/ExcelBlog/label-name/Office%20Scripts) for updates on Office Scripts features. You can also stay subscribed to this issue and I'll update it if the VS Code for Office Scripts feature returns.
