### ISSUE TITLE
Move rows across tables additional filters

### ISSUE THREAD

**Issue by JohnHotham** [OfficeDev/office-scripts-docs#666]
Hi Folks

I'm hoping that I can consolidate some coding, or find a piece of code that can bridge three separate scripts together to form one action.

"A bit like creating three VBA Sub scripts then creating a private sub as the action sub"

While I have posed the question to the video presenter (YouTube Channel) for what I am looking for, I do understand and appreciate that he may well be a busy chappy, so I'll ask it here with the same hope of finding an answer.

The script is great, to begin with, and does the job as prescribed, more so now that I have to move away from the conventional VBA when playing with SharePoint.  I noticed something in the video about applying additional filters, but this was not explored further and have not been able to locate coding elsewhere.

Two questions:
How do I adjust the script to check the column (36) that the script is searching to check for other criteria - as you would with filtering data, ie. If (36) = Data1, and or Data2, and or Data3 - display, select - one, more, all or nothing.  So it will not matter if one or all three or none are there it will move whatever data is found.

The other aspect was pasting the final values and "formatting".

Thanks for looking in and reading, and hope you can offer some guidance

Regards
[]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2e9f5a-e7c8-b6b1-c3fa-c64934ca2eda
* Version Independent ID: 431cbb17-07a5-cead-41b0-e622672f5d63
* Content: [Move rows across tables using Office Scripts - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/move-rows-across-tables)
* Content Source: [docs/resources/samples/move-rows-across-tables.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/move-rows-across-tables.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @JohnHotham,

Thank you for the questions. I'm not quite sure I understand the scenario you're trying to accomplish, but I'll try my best.

First, you can't call a script from another script. You can have your script call multiple functions, like this:
```
 function main(workbook: ExcelScript.Workbook) {
    const selectedSheet = workbook.getActiveWorksheet();
    for (let i = 0; i < 10; i++) {
        for (let j = 0; j <= i; j++) {
            highlightCell(selectedSheet.getRangeByIndexes(i, j, 1, 1));
        }
    }
}

function highlightCell(cell: ExcelScript.Range) {
    cell.getFormat().getFill().setColor("yellow");
}
```

You could also call multiple scripts from Power Automate. [This scenario](https://learn.microsoft.com/en-us/office/dev/scripts/resources/scenarios/task-reminders) shows a flow that calls multiple scripts on the same workbook (granted, there are intermediate steps in the sample).

As for the filter question, if you want to apply a value-based filter, you'll `applyValuesFilter` on the Filter object of the TableColumn. In this example, the filter will only show rows when the value in the Description Rating is "Good" or "Fine".

```
function main(workbook: ExcelScript.Workbook) {
    const coverageWorksheet = workbook.getWorksheet("Coverage");
    const coverageTable = coverageWorksheet.getTable("CoverageTable");
    const descriptionColumn = coverageTable.getColumnByName("Description Rating");
    const descriptionSet = columnToSet(descriptionColumn);
    descriptionColumn.getFilter().applyValuesFilter(["Good", "Fine"]);
}
```

If you want to make a filter that keeps everything _except_ a certain value, you'll need to add every other value to that filter array. In this example, we'll keep every row that doesn't have a description rating of "Poor". We'll use a helper function that converts all the values in a column to a set (effectively turning a 2D-array with duplicates into a 1D-array with unique values).

```
function main(workbook: ExcelScript.Workbook) {
    const coverageWorksheet = workbook.getWorksheet("Coverage");
    const coverageTable = coverageWorksheet.getTable("CoverageTable");
    const descriptionColumn = coverageTable.getColumnByName("Description Rating");
    const descriptionSet = columnToSet(descriptionColumn);
    descriptionColumn.getFilter().applyValuesFilter(descriptionSet.filter((value) => {
        return value !== "Poor";
    }));
}

/**
 * Convert a column into a set so it only contains unique values.
 */
function columnToSet(column: ExcelScript.TableColumn): string[] {
    const range = column.getRangeBetweenHeaderAndTotal().getValues() as string[][];
    const columnSet: string[] = [];
    range.forEach((value) => {
        if (!columnSet.includes(value[0])) {
            columnSet.push(value[0]);
        }
    });

    return columnSet;
}
```

I hope that helps. Please let me know if I missed the mark.

**Comment by AlexJerabek** [comment]
Sounds good. Please let me know if that helps. If so, I'll work on creating a sample so others can benefit.
