### ISSUE TITLE
Tutorial: Update a spreadsheet from a Power Automate flow need update.

### ISSUE THREAD

**Issue by Fran-Rochalima** [OfficeDev/office-scripts-docs#679]
The tutorial needs to be updated. UI changes. No button "Next Step (item 5. to 8.)". Open imediatly the flow and have to click on the "+" to insert a action.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b951170-8016-6d95-be28-575a0e728c4b
* Version Independent ID: 42b9d09a-9e39-f9ed-c278-d40982c8defc
* Content: [Tutorial: Update a spreadsheet from a Power Automate flow - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/tutorials/excel-power-automate-manual)
* Content Source: [docs/tutorials/excel-power-automate-manual.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/tutorials/excel-power-automate-manual.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this. It looks like the Power Automate UI has changed across the board. I'll work on updating all the docs this week.
