### ISSUE TITLE
Script converting then corrupt XLSX?

### ISSUE THREAD

**Issue by jamiechalmerzlp** [OfficeDev/office-scripts-docs#700]
Basically I am trying to modify the flow to work dynamically so when an email comes in with a subject filter of "XXX" then 'Loop' to create files saving the attachments, then it moves on to the flow documented here https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv however, it does create the XLSX but they are corrupt so when I try to open the doucments, they don't open and I get an error stating 'This workbook couldn't be opened because the file format may not be matching with the file extension.' Also note, my workbook sheet for the CSV is not called 'Sheet1' so I don't know if that is having an impact on it. Please help ASAP :(

## Article URL
(https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv

**Comment by jamiechalmerzlp** [comment]
Hey @AlexJerabek thanks for the sharp response. In all honesty, I have not tried it with the test documents as I had my own CSV that I needed it to function with so I had been testing with that. I have attached an image of my flow. The top half just saves the email attachments to a folder called 9x9, the bottom half follows the 
![msedge_EM5Pzop9Ku](https://github.com/OfficeDev/office-scripts-docs/assets/78878449/ee1da526-0acc-42f8-b948-0c21d6d9593c)

**Comment by AlexJerabek** [comment]
Thanks for sharing the flow screenshot. I can't see anything wrong, so we're going to have to try a couple debugging steps.

1. If you remove the **Run script** step, are you able to open the XLSX files?
2. When you test the flow, you can select each step after it runs to see the output. Does the .csv output look normal in your **Get File Content Dynamically For CSVs** step? Here's my output from the test files.
![image](https://github.com/OfficeDev/office-scripts-docs/assets/38896772/61decf2a-e3e8-47dd-b38f-49ab50322aed)

**Comment by jamiechalmerzlp** [comment]
Hey Alex, so I have it working now to copy the contents from the csv to the newly created xlsx, however, I am still seeing "" around the strings on the spreadsheet, indicating to me that there must be something wrong on my end of course. However, I have done step by step everything the guide states to me. Can you possibly take this to PM with me so that I can share the screenshots without releasing employee data? Many thanks
