### ISSUE TITLE
Enabling the service does not enable the service

### ISSUE THREAD

**Issue by erobillard** [OfficeDev/office-scripts-docs#71]
## Article URL
[Tutorial](https://docs.microsoft.com/en-us/office/dev/scripts/tutorials/excel-tutorial)
[Office Scripts settings in M365](https://support.office.com/en-us/article/office-scripts-settings-in-m365-19d3c51a-6ca2-40ab-978d-60fa49554dcf)

## Issue
The first article indicates the service is enabled per user, but the steps to enable Office Scripts in the 2nd link are tenant-wide. Also, enabling the service has no effect in the Excel Web UI, hoping for either an updated timeline for availability.

**Comment by AlexJerabek** [comment]
Hi @erobillard, 
Thanks for reporting this. I'll look into the documentation discrepancy. 

@gergzk, can you look into the UI not showing the automate tab?

**Comment by AlexJerabek** [comment]
I corrected the tutorial with PR #75.  It now correctly states the scope of an admin enabling Office Scripts. The change will be merged into the production documentation soon.
We're still looking into your issue of the Automate tab not showing up.

**Comment by AlexJerabek** [comment]
Hi @erobillard,

Office Scripts is currently in Targeted release. The feature has not reached all Excel on the web users and organizations yet. The article [Set up the Standard or Targeted release options in Office 365](https://docs.microsoft.com/office365/admin/manage/release-options-in-office-365) has information on how to opt-in to early feature releases. Even within the targeted release, it may be a bit before everyone sees Office Scripts. There's a release throttle built in to avoid scaling too fast. 

If your admin has enabled Office Scripts, you will see the Automate tab once the latest version of Excel on the web reaches your organization.

I've submitted updates to support.office.com to make this more clear. I'll close this issue for now, but please respond if you need more information. Thanks!
