### ISSUE TITLE
Wrong title of sample code

### ISSUE THREAD

**Issue by Drout** [OfficeDev/office-scripts-docs#712]
### Type of issue

Typo

### Feedback

In this section: Sample 2: Write data in batches from a Power Automate flow
The sample code to **write** the rows to an excel sheet has wrong title: _Sample code: Read selected rows_
Should be: _Write selected part of a Workbook_ or similar

### Page URL

https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/write-large-dataset?view=office-scripts

### Content source URL

https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/write-large-dataset.md

### Author

@o365devx

### Document Id

3d2c2ca4-de3f-5894-82d3-b69771574480

**Comment by AlexJerabek** [comment]
Hi @Drout,

Thanks for reporting this. I'll get that fixed right now.
