### ISSUE TITLE
The wrong chart type

### ISSUE THREAD

**Issue by kvazirinejad** [OfficeDev/office-scripts-docs#724]
### Type of issue

Typo

### Feedback

Hello,

I noticed a discrepancy in the code provided within the chart section. While the author used ExcelScript.ChartType.columnStacked, the displayed chart appears to be a Column clustered chart. It would be beneficial to adjust the code to ExcelScript.ChartType.columnClustered to accurately reflect the chart's appearance.

Thank you for sharing this informative article.

Best regards,
Karim

### Page URL

https://learn.microsoft.com/en-us/office/dev/scripts/develop/scripting-fundamentals

### Content source URL

https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/scripting-fundamentals.md

### Author

@o365devx

### Document Id

bf0955e2-2a06-ea7d-3d78-c8c52294d23a

**Comment by AlexJerabek** [comment]
Hi @kvazirinejad,

Thanks for reaching out. I just double-checked and the image is showing the correct chart type. Both charts look very similar in this scenario when there aren't multiple values for each category.

![image](https://github.com/OfficeDev/office-scripts-docs/assets/38896772/760fef2e-6cbf-4473-9758-8124ee3cdfdb)
 
 I'm going to close the issue, but if there's something I'm missing, please leave a comment and I'll reopen the issue.
