### ISSUE TITLE
Platfrom support is inconsistent with other documentations

### ISSUE THREAD

**Issue by gemdav** [OfficeDev/office-scripts-docs#743]
Hey there!

If I don't miss out on something, the platform support table is inconsistent with the Office (Web) Add-In documentation. 

While the Office (Web) Add-In documentation states that COM Add-Ins are not supported on Mac ...

https://github.com/OfficeDev/office-js-docs-pr/blob/453aa14f32920acf2f193cc8330cb206038f298a/docs/overview/office-add-ins.md?plain=1#L24

..., the platform support table of this documentation states that they are (at least for Excel).

https://github.com/OfficeDev/office-scripts-docs/blob/8812463e4523ee63075854a6a7f151c6dec77623/docs/includes/platform-support-table.md?plain=1#L1-L7

It would be nice to have consistent documentation on this topic or clarification on how and why COM Add-ins are supported on Excel on the Mac but not generally supported on Mac.

**Comment by slabereemsft** [comment]
@grangeryy - COM add-in documentation question.

**Comment by AlexJerabek** [comment]
Hi @gemdav,

I confirmed with @gergzk that COM is not supported on any applications on Mac. I'll update the table in the Office Scripts documentation to reflect that.

**Comment by gemdav** [comment]
Hi @AlexJerabek,

That supports my understanding of COM Add-Ins. Thanks for confirming this. I really appreciate it.
