### ISSUE TITLE
Corrupt File

### ISSUE THREAD

**Issue by philsmash** [OfficeDev/office-scripts-docs#759]
When I set this up it creates the new excel file but when trying to open it tells me that it's corrupt.

**Comment by alison-mk** [comment]
Hi @philsmash, thanks for submitting an issue. Are you following a tutorial or sample in the Office Scripts documentation? If so, can you provide a link to the page that you're using? I'd like to test out the tutorial or sample myself to see if I can replicate your issue. 

Thanks, 
Alison
